### ISSUE TITLE
Double y rotation on the rotation matrix for rendering

### ISSUE THREAD

**Issue by Minitte** [Minitte/Leap-N-Lost#55]
Appears that the rotation matrix for rendering rotates by the y axis twice.

```
var rotationMatrix : GLKMatrix4 = GLKMatrix4RotateX(GLKMatrix4Identity, gameObject.rotation.x);

rotationMatrix = GLKMatrix4RotateY(rotationMatrix, gameObject.rotation.y);

rotationMatrix = GLKMatrix4RotateY(rotationMatrix, gameObject.rotation.z);
```

https://github.com/Minitte/Leap-N-Lost/blob/657a8def867e90169526f21b541ef7fa94658e0a/LeapNLost/LeapNLost/Engine/GameEngine.swift#L281

**Comment by Minitte** [comment]
Is this intentional?

**Comment by awongs** [comment]
Nope that's definitely a typo
